name: abeja
rules:
  - when:
      red: 0
      green: 0
      blue: 1
      black: 0
    image: abeja.png
    text: null
  - when:
      red: 1
      green: 0
      blue: 0
      black: 0
    image: panal.png
    text: null
  - when:
      red: 1
      green: 0
      blue: 1
      black: 0
    image: panal-abeja.png
    text: null
  - when:
      red: 0
      green: 1
      blue: 0
      black: 0
    image: flor.png
    text: null
  - when:
      red: 0
      green: 1
      blue: 1
      black: 0
    image: flor-abeja.png
    text: null
  - when:
      red: 0
      green: 2
      blue: 0
      black: 0
    image: flor-polinizada (1).png
    text: null
  - when:
      red: 0
      green: 0
      blue: 0
      black: 2
    image: planta1.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 1
      black: 2
    image: planta1-abeja.png
    text: null
  - when:
      red: '*'
      green: '*'
      blue: '*'
      black: '*'
    image: fondo (2).png
    text: null
