library:
  visible: false
source:
  visible: true
  percentage: 0.440625
board:
  visible_edition: true
  collapse_toolbox: false
  user_permissions:
    can_change_initial_board: true
    can_change_initial_board_source: false
    can_edit_board: false
    can_view_size_section: true
    can_view_attire_section: true
  active: 1
  initial_board_source: selected
execution_speed:
  user_permissions:
    can_change_speed: true
  active: high
attire:
  user_permissions:
    can_toggle_visibility: true
  visible: true
  active: abeja
initialDescription: true
link: ''
blocks:
  visible:
    - ComandosPrimitivos
    - ProcedimientosPrimitivos
    - MisProcedimientos
    - Alternativas
    - Repeticiones
    - CategoriaAsignacion
    - Literales
    - ExpresionesPrimitivas
    - FuncionesPrimitivas
    - MisFunciones
    - Operadores
    - Definiciones
  disabled: []
activity:
  creation_mode: advanced
  construction_mode: blocks
  execution_type: sequential
name: 'La abeja del mes '
