name: minero
rules:
  - when:
      red: 1
      green: 0
      blue: 0
      black: 0
    image: minero.png
    text: null
  - when:
      red: 0
      green: 1
      blue: 0
      black: 0
    image: esmeralda.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 1
      black: 0
    image: oro.png
    text: null
  - when:
      red: 1
      green: 1
      blue: 0
      black: 0
    image: minero-esmeralda.png
    text: null
  - when:
      red: 1
      green: 0
      blue: 1
      black: 0
    image: minero-oro.png
    text: null
  - when:
      red: 2
      green: 0
      blue: 0
      black: 0
    image: excavadora.png
    text: null
  - when:
      red: 2
      green: 0
      blue: 1
      black: 0
    image: excavadora-oro.png
    text: null
  - when:
      red: '*'
      green: '*'
      blue: '*'
      black: '*'
    image: fondo (3).png
    text: null
