name: Erizo
rules:
  - when:
      red: 0
      green: 1
      blue: 0
      black: 0
    image: erizo.png
    text: null
  - when:
      red: 1
      green: 0
      blue: 0
      black: 0
    image: globo.png
    text: null
  - when:
      red: 0
      green: 2
      blue: 0
      black: 0
    image: erizo.png
    text: null
  - when:
      red: 1
      green: 1
      blue: 0
      black: 0
    image: erizo-globo.png
    text: null
  - when:
      red: 1
      green: 2
      blue: 0
      black: 0
    image: erizo-pinchando.png
    text: null
  - when:
      red: 2
      green: 2
      blue: 0
      black: 0
    image: erizo-globo-explotado.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 0
      black: 1
    image: globo roto.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 0
      black: 0
    image: fondo.png
    text: null
