library:
  visible: false
source:
  visible: true
  percentage: 0.55
board:
  visible_edition: true
  collapse_toolbox: false
  user_permissions:
    can_change_initial_board: true
    can_change_initial_board_source: false
    can_edit_board: false
    can_view_size_section: true
    can_view_attire_section: true
  active: 1
  initial_board_source: selected
execution_speed:
  user_permissions:
    can_change_speed: true
  active: superhigh
attire:
  user_permissions:
    can_toggle_visibility: true
  visible: false
  active: Calles
initialDescription: true
link: ''
blocks:
  visible:
    - Comandos
    - Expresiones
    - Definiciones
  disabled: []
activity:
  creation_mode: advanced
  construction_mode: blocks
  execution_type: sequential
name: Calles para todos
