name: Sapo
rules:
  - when:
      red: 0
      green: 1
      blue: 0
      black: 0
    image: sapo.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 1
      black: 0
    image: mosca.png
    text: null
  - when:
      red: 0
      green: 1
      blue: 1
      black: 0
    image: sapo-mosca.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 0
      black: 1
    image: abeja.png
    text: null
  - when:
      red: 0
      green: 1
      blue: 0
      black: 1
    image: sapoAbeja.png
    text: null
  - when:
      red: 0
      green: 2
      blue: 0
      black: 1
    image: sapoAbejaSalta.png
    text: null
  - when:
      red: '*'
      green: '*'
      blue: '*'
      black: '*'
    image: fondo.png
    text: null
