library:
  visible: false
source:
  visible: true
  percentage: 0.5499977122986823
board:
  visible_edition: true
  collapse_toolbox: false
  user_permissions:
    can_change_initial_board: false
    can_change_initial_board_source: false
    can_edit_board: false
    can_view_size_section: false
    can_view_attire_section: true
  active: 1
  initial_board_source: selected
execution_speed:
  user_permissions:
    can_change_speed: true
  active: high
attire:
  user_permissions:
    can_toggle_visibility: true
  visible: false
  active: Laberinto
initialDescription: true
link: ''
blocks:
  visible:
    - DefinicionDeProcedimientoSimple
    - ProcedimientosPrimitivos
    - MisProcedimientos
    - ComandosPrimitivos
    - Color
    - Direccion
    - ExpresionesPrimitivas
activity:
  type: Sin dominio
  toolbox: Inicial
  creation_mode: basic
  construction_mode: blocks
  execution_type: sequential
name: Buscando la salida
